### ISSUE TITLE
Not Working!

### ISSUE THREAD

**Issue by pkhodaveissi** [react-native-kit/react-native-track-player-demo#3]
It hangs after printing below lines when initialized by `npm run start`:

```
React packager ready.

Loading dependency graph, done.
```

**Comment by pkhodaveissi** [comment]
even if ran with react-native-cli it still outputs errors on ios 
`Print: Entry, ":CFBundleIdentifier", Does Not Exist react native`

**Comment by Guichaguri** [comment]
This demo is outdated at the moment, use the [example app](https://github.com/react-native-kit/react-native-track-player/tree/dev/example) for a reference instead.

**Comment by pkhodaveissi** [comment]
tnx, I'll try it

**Comment by pkhodaveissi** [comment]
is there any kind of specific instruction in order to run the example project?

**Comment by pkhodaveissi** [comment]
@Guichaguri can you tell me what I'm doing wrong?

```
Installing build/Build/Products/Debug-iphonesimulator/example.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/example.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist


Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/example.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:621:11)
    at Object.execFileSync (child_process.js:639:13)
    at Promise.then (/Users/pierre/work/react-ex/react-native-track-player-dev/example/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)
```
